### ISSUE TITLE
Ureditev uvoza

### ISSUE THREAD

**Issue by 20timresnik** [20timresnik/APPR-2018-19#2]
Dober dan,

zanima me, če so urejeni podatki, torej tabele iz uvoza primerne, v stilu tidy data, za nadaljevanje pri vizualizaciji me zanima na kakšen način mislite da bi bilo najbolje seštevati skupen bdp(podatke imam po kvartalih); da naredim v tabelah dodaten stolpec z vsoto bdp-ja(kar se mi ne zdi najboljša ideja) ali da napišem novo funkcijo ki računa vsoto za željeno državo in leto, ter vrne novo tabelo oz. podatek z želenimi podatki(tega sicer ne vem kako bi točno naredil). Hvala za odgovor

**Comment by jaanos** [comment]
Najprej, pri navajanju datotek podajaj pot, relativno na vrhnjo mapo repozitorija - glede na to, da imaš podatke v mapi `podatki`, torej navedi npr. `"podatki/PodatkiSlovenija.csv"`. Poleg tega svetujem, da namesto funkcije `parse_factor` (če ne podajaš parametra `levels`) raje uporabiš kar funkcijo `factor`, saj sicer ne bo delovalo s starejšimi različicami knjižnice `readr` (pri novejših različicah so nekateri drugi problemi, tako da bo zaenkrat bolje poskrbeti za združljivost za nazaj). Seveda poskrbi, da imaš v RStudiu odprt projekt - če desno zgoraj piše *Project: (None)*, klikni tja, izberi *Open Project...*, nato pa poišči datoteko `APPR-2018-19.Rproj` v mapi svojega repozitorija (tako bo deloval tudi git znotraj RStudia).

Obe razpredelnici izgledata oblikovani skladno z obliko *tidy data* - svetoval bi le, da kvartale predstaviš kar s številom (uporabi kar `parse_number` - po potrebi jih lahko vedno pretvoriš nazaj v faktorje s `factor`). Poleg tega se raje izogibaj šumnikom, presledkom in ostalim posebnim znakom v imenih stolpcev - zadnji stolpec v obeh razpredelnicah naj ima raje kakšno krajše ime. Pri razpredelnici `podatki.slovenija` imaš sicer kategorijo *..od tega: C Predelovalne dejavnosti*, ki je vključena že v kategorijo *BCDE*. Svetujem torej, da bodisi odstraniš vrstice za predelovalne dejavnosti, ali pa jih izločiš iz *BCDE* (tj., odšteješ vrednosti in kategorijo ustrezno preimenuješ).

Če prav razumem, želiš skupen BDP za posamezno državo v posameznem kvartalu dobiti kot vsoto postavk za vsako dejavnost. To bi šlo nekako tako:
```R
bdp.evropa <- podatki.evropa %>% drop_na(5) %>% group_by(Drzava, Leto, Kvartal) %>%
  summarise(BDP=sum(`Stalne cene, referenčno leto 2010, v mio €`, na.rm=TRUE))
```
Funkcija `drop_na` iz knjižnice `tidyr` tukaj poskrbi, da se izpustijo vrstice s praznimi vrednosti v petem stolpcu - tako v dobljeni razpredelnici ne bo ničelnih vsot za države, za katere v določenem kvartalu ni nobenih podatkov. Če boš razpredelnico potreboval samo na enem mestu (npr. za izris nekega grafa ali zemljevida), je seveda ni potrebno shranjevati v spremenljivko.

**Comment by 20timresnik** [comment]
Hvala za odgovor in pomoč, v uvozu sem popravil pot datotek katero odpiram, *parse_factor* sem zamenjal z *as.factor* in odstranil iz tabele dejavnost C, ki se je potem pojavila v skupni dejavnosti BCDE.

Pri začetku vizualizacije sem uporabil sem tudi vašo predlagano funkcijo, ki ste jo napisali v temu *issue-u*. Potem sem poskusil spisati še dve funkciji, zelo podobni tej, za lažje delo v nadaljevanju(vsota po kvartalih in vsota za slovenijo) vendar sem naletel na težavo, saj mi *summarise* ni želel sprejeti vrednosti, katero želim seštevati. Verjetno bo bolj jasno kaj mislim, če pogledate v datoteko vizualizacija, omenjeni funkciji sem označil s komentarjem(znakom #).

Zanima me tudi, če je v redu, da sem pri vizualizaciji npr. *slovenia* dal v data.frame, saj mi drugače grafa ni želelo narisati, ali obstaja kakšen drug razlog za to, ali je to najelegantnejša rešitev?

Hvala za vaš odgovor

**Comment by jaanos** [comment]
Pri funkcijah iz knjižnice `dplyr` (npr. `filter`, `select`, `mutate`, `group_by`, `summarise` itd.) lahko imena stolpcev podajaš brez navednic - če seveda ti ne vsebujejo presledkov ali drugih posebnih znakov (v zgornjem primeru je bilo tako, zato je bilo potrebno ime stolpca postaviti med znaka \` - na slovenski tipkovnici ga dobiš z desnim Alt + 7).

Podobno stolpce navajaš tudi v funkciji `aes` pri risanju grafov z `ggplot`. Če torej narediš
```R
sl <- ggplot(slovenia) + aes(x=Leto, y=BDP) + geom_point()
```
potem pretvorba z `as.data.frame` ne bo potrebna.
