### ISSUE TITLE
Pomoč pri grafih

### ISSUE THREAD

**Issue by 20timresnik** [20timresnik/APPR-2018-19#3]
Pozdravljeni,

prosil bi za pomoč pri oblikovanju grafov, par malenkosti ne znam postoriti sam. Pri prvem grafu, ki ga imam pri vizualizaciji, ne znam narediti, da so stolpci za posamezno državo eden zraven drugega, sedaj se mi pokrivajo, mislil sem da bom zadevo rešil z *position = position_dodge()* vendar ni delovalo; graf je enak kot prej. Nevem kako bi odstranil iz x osi leto 1995, verjetno že v prvi vrstici pri definiranju *ggplot*?

Pri drugem grafu sem želel posamezen sektor predstaviti v primerjavi z letom 1995, se pravi za kolikokrat se je od takrat nominalno povečal. To sem rešil s tem da sem vzel za začetno vrednost sektor BCDE iz leta 1995 in nato ostale pomnožil s faktorjem, ki so ga imeli v primerjavi s tem sektorjem v letu 1995. Zadeva je malo čudna, ali imate kakšen predlog, kako bi se lahko vsi sektorji začeli v letu 1995 iz iste točke, nato pa povečevali/zmanjševali glede na nominalno spremembo skozi leta; v zdajšnjem grafu imam namreč na y osi dejanski nek BDP, ki pa ni natančen saj je to zmnožek s faktorjem iz leta 1995-tega dejansko ne rabim, samo ne vem kako bi rešil zadevo.

Za oba grafa me tudi zanima, kako lahko dodam legendo na desni strani, da se vidi katera barva predstavlja katero državo, do sedaj so bili moji poskusi žal neuspešni.

Zahvaljujem se za vašo pomoč.

**Comment by jaanos** [comment]
Če želiš prikazati stolpce za različne države, potem filtriraj po teh državah in podaj državo kot parameter `fill` pri funkciji `aes`, npr.
```R
graf1 <- ggplot(bdp.evropa %>%
                  filter(Drzava %in% c('Germany (until 1990 former territory of the FRG)',
                                       'Spain', 'Greece', 'Slovenia', 'Czechia'),
                         Leto %in% 1996:2017), aes(x=Leto, y=BDP/1e6, fill=Drzava)) +
  geom_col(position="dodge") + xlab("Leto") + ylab("BDP v milijonih €") +
  ggtitle("Primerjava petih držav") + theme(axis.title=element_text(size=11),
                                            plot.title=element_text(size=15, hjust=0.5))
```
Zgornji graf sicer prikaže samo BDP v milijonih evrov (da se izogneš eksponentni notaciji v oznaki osi *y*). Seveda je bolj smiselno, če te podatke deliš s številom prebivalcev, ko že počneš - za to pa bo te podatke potrebno uvoziti (npr. v svojo razpredelnico) in združiti s tvojimi podatki (npr. z `inner_join`) - potem lahko podatke na osi *y* dobiš tako, da deliš ustrezna stolpca.

Podobno lahko narediš tudi pri drugem grafu. Tukaj bo treba pridružiti podatke iz leta 1995, da lahko prikažeš relativno rast glede nanje:
```R
graf2 <- ggplot(bdp.kvartali.slovenija %>% ungroup() %>%
                  filter(Leto == 1995,
                         Dejavnosti %in% c('A Kmetijstvo, lov, gozdarstvo, ribištvo',
                                           'BCDE Rudarstvo, predelovalne dejavnosti, oskrba z elektriko in vodo, ravnanje z odplakami, saniranje okolja',
                                           'J Informacijske in komunikacijske dejavnosti',
                                           'F Gradbeništvo',
                                           'K Finančne in zavarovalniške dejavnosti')) %>%
                  transmute(Dejavnosti, zacetniBDP=BDP) %>%
                  inner_join(bdp.kvartali.slovenija) %>% filter(Leto != 2018),
                aes(x=Leto, y=BDP/zacetniBDP, color=Dejavnosti)) +
  geom_line(size = 2) + xlab("Leto") + ylab("Rast/padanje") +
  ggtitle("Spreminjanje nominalnega deleža dejavnosti A, BCDE, F, J in K")
```

V obeh primerih se tudi že izriše legenda (zaradi parametra `fill` oziroma `color` pri `aes`). Svetujem sicer, da v podatkih spremeniš oznake, da ne bodo oznake v legendah predolge.
