### ISSUE TITLE
Zemljevid

### ISSUE THREAD

**Issue by 20timresnik** [20timresnik/APPR-2018-19#4]
Dober dan,

prosil bi za pomoč pri urejanju zemljevida. Najprej bi rad zemljevid, ki ga imam pomanjšal samo na Evropo(sedaj je na njem celoten svet), ali to storil z omejitvijo geografske širine in dolžine, ali na kakšen drug način? Sestavil sem novo tabelo *bdp.evropa.2017*, ki predstavlja vsoto bdp-ja za vsako državo evrope v letu 2017, iz nje bi namreč rad narisal zemljevid; države z večjim bdp bodo obarvane temneje, tiste z manjši pa svetleje. Če prav razumem, moram to tabelo *left_join* oz. *right_join* s tisto v kateri imam shranjen zemljevid? Hvala za pomoč, pri zemljevidih sem na trenutno na mrtvi točki in res ne vem kaj naj storim, da bo izrisan v obliki ki si ga želim.

Lep pozdrav, Tim

**Comment by jaanos** [comment]
Najbolje, da uporabiš kar oba pristopa - po eni strani lahko zemljevid filtriraš tako, da prikažeš le želene države (in tako ostalih držav sploh ne izrisuješ), po drugi strani pa ne želiš prikazati celotne Rusije. Filtriraš lahko po stolpcu `CONTINENT`, pri čemer bo treba posebej poskrbeti za Turčijo in Ciper:
```R
evropa <- zemljevid %>% filter(CONTINENT == "Europe" | NAME %in% c("Turkey", "Cyprus"))
```
Sedaj lahko narišeš graf s svojimi podatki, npr.
```R
ggplot() + geom_polygon(data=evropa %>% left_join(bdp.evropa.2017, by=c("NAME"="Drzava")),
                        aes(x=long, y=lat, group=group, fill=BDP)) +
  coord_cartesian(xlim=c(-25, 40), ylim=c(35, 72))
```

Naj opozorim, da npr. Nemčija ni pobarvana, saj je v podatkih uporabljeno drugačno ime kot na zemljevidu. Svetujem torej, da v podatkih popraviš imena tako, da bodo ustrezala zemljevidu.

**Comment by 20timresnik** [comment]
Sem popravil imena in malo sprobal z barvami ter dela, hvala. Vprašal bi še za pomoč pri risanju grafa4 ki ga imam v vizualizaciji. Rad bi analiziral razliko v kvartalih za izbrane dejavnosti(*A, BCDE, J, F, K*), se pravi bi naredil za vsako dejavnost graf kjer bi se videla razlika po kvartalih, torej za vsako leto na x-osi, štirje kvartali(to sem mislil narisati z *geom_point*; ali je to dobra ideja?) te grafe pa bi "razporedil" enega ob drugem z *facet_grid*, da ne bi predstavljali vsak zase cel graf ker niso tako pomembni, vendar mi tega ne uspe narediti. 

Hvala za pomoč, Tim

**Comment by jaanos** [comment]
Nisem čisto prepričan, kaj točno želiš doseči - so pa v trenutni kodi napačno postavljeni oklepaji (`facet_grid` in `geom_point` morata biti prišteta izven `ggplot`). Nekaj takega bi šlo:
```R
graf4 <- ggplot(bdp.kvartali.slovenija %>% 
                  filter(Dejavnosti %in% c('A Kmetijstvo, lov, gozdarstvo, ribištvo',
                                           'BCDE Rudarstvo, predelovalne dejavnosti, oskrba z elektriko in vodo, ravnanje z odplakami, saniranje okolja',
                                           'J Informacijske in komunikacijske dejavnosti',
                                           'F Gradbeništvo',
                                           'K Finančne in zavarovalniške dejavnosti'),
                  Leto != 2018),
                aes(x=Leto, y=BDP, color=factor(Kvartal))) +
  facet_grid(cols=vars(Dejavnosti)) + geom_point(size=2)
```
