### ISSUE TITLE
Shiny zemljevid

### ISSUE THREAD

**Issue by 20timresnik** [20timresnik/APPR-2018-19#5]
Dober dan,

žal sem naletel na prepreko pri svojem projektu, težave mi namreč povzroča delovanje shiny zemljevida, pri katerem bi si želel, da bi uporabnik izbral leto, nato pa bi se mu izrisal zemljevid, obarvan glede na višino BDP-ja držav Evrope za tisto leto. Res mi ne uspe napisati kode pravilno, da bi stvar delala, ali je kaj mogoče narobe s podatki? Mislim, da bi drugače morali biti v redu, nahajajo se v *bdp.evropa*, tako da je težava verjetno nekje drugje?

Hvala za pomoč, Tim

**Comment by jaanos** [comment]
Problem je v tem, da imata oba izbirnika v `ui.R` ime `id_poz`, tako da se pri izrisovanju zemljevida namesto leta uporabi dejavnost. Če spremeniš ime izbirnika za leto (in ustrezno še izrisovanje zemljevida), bi moralo delovati.
